# Generated by Django 5.2 on 2025-12-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0002_post_likes_alter_post_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="カテゴリ名")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="カテゴリ説明"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EmailGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=100, verbose_name="相手の名前・役職"),
                ),
                ("context_notes", models.TextField(verbose_name="伝えたい要件・状況")),
                (
                    "tone_setting",
                    models.CharField(
                        choices=[
                            ("formal", "極めて丁寧"),
                            ("standard", "標準"),
                            ("soft", "柔らかめ"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="トーン設定",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="生成された件名"),
                ),
                ("body", models.TextField(verbose_name="生成された本文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, verbose_name="ユーザーによる修正有無"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testApp.category",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成ユーザー",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
