# Generated by Django 5.2 on 2025-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0003_category_remove_post_author_remove_post_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
