# Generated by Django 5.2 on 2026-01-02 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0004_delete_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailgeneration",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "ビジネス全般"),
                    ("apology", "お詫び・謝罪"),
                    ("thank_you", "お礼・感謝"),
                    ("request", "依頼・お願い"),
                    ("notice", "通知・お知らせ"),
                    ("greeting", "挨拶（季節・転勤など）"),
                ],
                default="business",
                max_length=50,
                verbose_name="カテゴリ",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="emailgeneration",
            options={},
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="tone_setting",
            field=models.CharField(
                default="標準", max_length=50, verbose_name="トーン設定"
            ),
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
