# Generated by Django 5.2 on 2026-01-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0005_alter_emailgeneration_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailgeneration",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "ビジネス全般"),
                    ("apology", "お詫び・謝罪"),
                    ("thank_you", "お礼・感謝"),
                    ("request", "依頼・お願い"),
                    ("notice", "通知・お知らせ"),
                    ("greeting", "挨拶（季節・転勤など）"),
                ],
                default="business",
                max_length=50,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AlterField(
            model_name="emailgeneration",
            name="tone_setting",
            field=models.CharField(
                choices=[
                    ("standard", "標準（失礼なく一般的）"),
                    ("polite", "とても丁寧（目上の人へ）"),
                    ("friendly", "親しみやすく（柔らかめ）"),
                    ("concise", "簡潔に（急ぎ・チャット）"),
                    ("apologetic", "お詫びの気持ちで"),
                ],
                default="standard",
                max_length=50,
                verbose_name="トーン設定",
            ),
        ),
    ]
